.Dd "June 14, 2014"
.Dt SNDFILE-INFO 1
.Os
.Sh NAME
.Nm sndfile-info
.Nd display information about a sound file
.Sh SYNOPSIS
.Nm sndfile-info
.Ar file
.Sh DESCRIPTION
.Nm
will display basic information about a sound file such as
its format, its sample rate, and the number of channels.
This information is obtained using libsndfile
.Pq Lk http://www.mega-nerd.com/libsndfile/ .
.Sh AUTHORS
This manual page was originally written by
.An Joshua Haberman Aq Mt joshua@debian.org
for the Debian GNU/Linux system (but may be used by others).
Further additions have been made by
.An Erik de Castro Lopo Aq Mt erikd@mega-nerd.com .
