.Dd "June 19, 2014"
.Dt SNDFILE-CONVERT 1
.Os
.Sh NAME
.Nm sndfile-convert
.Nd convert sound files from one format to another
.Sh SYNOPSIS
.Nm sndfile-convert
.Op Ar encoding
.Ar input_file
.Ar output_file
.Sh DESCRIPTION
.Nm
converts sound files from one format to another using libsndfile
.Pq Lk http://www.mega-nerd.com/libsndfile/
to read and write the data.
.Pp
The format of the output file is determined
by the filename extension of the output file.
.Pp
The optional
.Ar encoding
parameter allows setting of the data encoding for the output file.
Run
.Dq sndfile-convert --help
for more information.
.Sh AUTHORS
This manual page was written by
.An Erik de Castro Lopo Aq Mt erikd@mega-nerd.com .
