.Dd "June 19, 2014"
.Dt SNDFILE-INFO 1
.Os
.Sh NAME
.Nm sndfile-info
.Nd display information about sound files
.Sh SYNOPSIS
.Nm sndfile-info
.Op Ar options
.Ar
.Sh DESCRIPTION
.Nm
displays basic information about sound files
such as format, number of channels, samplerate, and length.
The following options are recognized:
.Pp
.Bl -tag -compact -width channelmapXXXX
.It Fl -instrument
Display instrument info:
a base note, gain, velocity, key, and loop points.
.It Fl -broadcast
Display broadcast (BWF) info.
.It Fl -channel-map
Display channel map.
.It Fl -cart
Display the cart chunk of a WAV (or related) file.
.El
.Sh SEE ALSO
.Lk http://www.mega-nerd.com/libsndfile/
.Sh AUTHORS
.An Erik de Castro Lopo Aq Mt erikd@mega-nerd.com .
