[versions]
agp = "8.7.1"
minsdk = "21"
compilesdk = "35"
buildtools = "35.0.0"
ndk = "27.2.12479018"
cmake = "3.30.5"

vorbis = "1.3.7-android-r1"
opus = "1.5.2-android-r1"
flac = "1.4.3-android-r1"
mpg123 = "1.32.9-android-r1"
lame = "3.100-android-r1"

[libraries]
vorbis = { group = "org.xiph", name = "vorbis-android", version.ref = "vorbis" }
opus = { group = "org.xiph", name = "opus-android", version.ref = "opus" }
flac = { group = "org.xiph", name = "flac-android", version.ref = "flac" }
mpg123 = { group = "de.mpg123", name = "mpg123-android", version.ref = "mpg123" }
lame = { group = "org.mp3dev", name = "lame-android", version.ref = "lame" }

[plugins]
library = { id = "com.android.library", version.ref = "agp" }
