include (CheckFunctionExists)
include (CheckIncludeFile)
include (CheckLibraryExists)
include (CheckTypeSize)
include (TestBigEndian)

function(def_check_include_file header_name result_name)
    check_include_file(${header_name} ${result_name})

    if (${result_name})
        add_definitions(-D${result_name})
    endif ()
endfunction ()

function(def_check_type_size type_name flag)
    check_type_size(${type_name} ${flag})

    if (${flag})
        add_definitions(-D${flag}=${${flag}})
    endif ()
endfunction ()

function(def_check_library_exists lib_name lib_func location result_name)
    check_library_exists(${lib_name} ${lib_func} "${location}" ${result_name})

    if (${result_name})
        add_definitions(-D${result_name})
    endif ()
endfunction ()

function(def_check_function_exists func_name result_name)
    check_function_exists (${func_name} ${result_name})

    if (${result_name})
        add_definitions(-D${result_name})
    endif ()
endfunction ()

if (WIN32)
    set(TYPEOF_SF_COUNT_T __int64)
else (UNIX)
    set(TYPEOF_SF_COUNT_T int64_t)
endif ()
set(SF_COUNT_MAX 0x7fffffffffffffffll)

find_package (ALSA)
if (ALSA_FOUND)
	add_definitions(-DHAVE_ALSA_ASOUNDLIB_H)
endif ()
def_check_include_file(byteswap.h       HAVE_BYTESWAP_H)
def_check_include_file(dlfcn.h          HAVE_DLFCN_H)
def_check_include_file(endian.h         HAVE_ENDIAN_H)
def_check_include_file(inttypes.h       HAVE_INTTYPES_H)
def_check_include_file(locale.h         HAVE_LOCALE_H)
def_check_include_file(memory.h         HAVE_MEMORY_H)
def_check_include_file(sndio.h          HAVE_SNDIO_H)
def_check_include_file(stdint.h         HAVE_STDINT_H)
def_check_include_file(stdlib.h         HAVE_STDLIB_H)
def_check_include_file(string.h         HAVE_STRING_H)
def_check_include_file(strings.h        HAVE_STRINGS_H)
def_check_include_file(sys/stat.h       HAVE_SYS_STAT_H)
def_check_include_file(bsys/time.h      HAVE_SYS_TIME_H)
def_check_include_file(sys/types.h      HAVE_SYS_TYPES_H)
def_check_include_file(sys/wait.h       HAVE_SYS_WAIT_H)
def_check_include_file(unistd.h         HAVE_UNISTD_H)

def_check_type_size(double                  SIZEOF_DOUBLE)
def_check_type_size(float                   SIZEOF_FLOAT)
def_check_type_size(int                     SIZEOF_INT)
def_check_type_size(${TYPEOF_SF_COUNT_T}    SIZEOF_SF_COUNT_T)
def_check_type_size(loff_t                  SIZEOF_LOFF_T)
def_check_type_size(long                    SIZEOF_LONG)
def_check_type_size(long\ long              SIZEOF_LONG_LONG)
def_check_type_size(offt64_t                SIZEOF_OFF64_T)
def_check_type_size(off_t                   SIZEOF_OFF_T)
def_check_type_size(short                   SIZEOF_SHORT)
def_check_type_size(size_t                  SIZEOF_SIZE_T)
def_check_type_size(ssize_t                 SIZEOF_SSIZE_T)
def_check_type_size(void*                   SIZEOF_VOIDP)
def_check_type_size(wchar_t                 SIZEOF_WCHAR_T)

def_check_library_exists (m floor "" HAVE_LIBM)
def_check_library_exists (sqlite3 sqlite3_close "" HAVE_SQLITE3)

def_check_function_exists(calloc		HAVE_CALLOC)
def_check_function_exists(free			HAVE_FREE)
def_check_function_exists(fstat         HAVE_FSTAT)
def_check_function_exists(fstat64		HAVE_FSTAT64)
def_check_function_exists(fsync         HAVE_FSYNC)
def_check_function_exists(ftruncate     HAVE_FTRUNCATE)
def_check_function_exists(getpagesize	HAVE_GETPAGESIZE)
def_check_function_exists(gettimeofday	HAVE_GETTIMEOFDAY)
def_check_function_exists(gmtime		HAVE_GMTIME)
def_check_function_exists(gmtime_r		HAVE_GMTIME_R)
def_check_function_exists(localtime     HAVE_LOCALTIME)
def_check_function_exists(localtime_r	HAVE_LOCALTIME_R)
def_check_function_exists(lseek         HAVE_LSEEK)
def_check_function_exists(lseek64		HAVE_LSEEK64)
def_check_function_exists(malloc		HAVE_MALLOC)
def_check_function_exists(mmap			HAVE_MMAP)
def_check_function_exists(open			HAVE_OPEN)
def_check_function_exists(pipe			HAVE_PIPE)
def_check_function_exists(read			HAVE_READ)
def_check_function_exists(realloc		HAVE_REALLOC)
def_check_function_exists(setlocale     HAVE_SETLOCALE)
def_check_function_exists(snprintf		HAVE_SNPRINTF)
def_check_function_exists(vsnprintf     HAVE_VSNPRINTF)
def_check_function_exists(waitpid		HAVE_WAITPID)
def_check_function_exists(write         HAVE_WRITE)
def_check_function_exists(ceil          HAVE_CEIL)
def_check_function_exists(floor         HAVE_FLOOR)
def_check_function_exists(fmod          HAVE_FMOD)
def_check_function_exists(lrint         HAVE_LRINT)
def_check_function_exists(lrintf        HAVE_LRINTF)
def_check_function_exists(lround        HAVE_LROUND)

TEST_BIG_ENDIAN(BIG_ENDIAN)
if (${BIG_ENDIAN})
    add_definitions(-DWORDS_BIGENDIAN=1)
    add_definitions(-DCPU_IS_BIG_ENDIAN=1)
    add_definitions(-DCPU_IS_LITTLE_ENDIAN=0)
else (${LITTLE_ENDIAN})
    add_definitions(-DWORDS_BIGENDIAN=0)
    add_definitions(-DCPU_IS_LITTLE_ENDIAN=1)
    add_definitions(-DCPU_IS_BIG_ENDIAN=0)
endif ()

if (WIN32)
    add_definitions(-DOS_IS_WIN32=1)
    add_definitions(-DUSE_WINDOWS_API=1)
    add_definitions(-DWIN32_TARGET_DLL=1)
    add_definitions(-D__USE_MINGW_ANSI_STDIO=1)
else (NOT WIN32)
    add_definitions(-DOS_IS_WIN32=0)
    add_definitions(-DUSE_WINDOWS_API=0)
    add_definitions(-DWIN32_TARGET_DLL=0)
    add_definitions(-D__USE_MINGW_ANSI_STDIO=0)
endif ()

