
include (CMake/functions.cmake)


mn_check_include_file (alsa/asoundlib.h	HAVE_ALSA_ASOUNDLIB_H)
mn_check_include_file (byteswap.h		HAVE_BYTESWAP_H)
mn_check_include_file (dlfcn.h			HAVE_DLFCN_H)
mn_check_include_file (endian.h			HAVE_ENDIAN_H)
mn_check_include_file (inttypes.h		HAVE_INTTYPES_H)
mn_check_include_file (locale.h			HAVE_LOCALE_H)
mn_check_include_file (memory.h			HAVE_MEMORY_H)
mn_check_include_file (sndio.h			HAVE_SNDIO_H)
mn_check_include_file (stdint.h			HAVE_STDINT_H)
mn_check_include_file (stdlib.h			HAVE_STDLIB_H)
mn_check_include_file (string.h			HAVE_STRING_H)
mn_check_include_file (strings.h		HAVE_STRINGS_H)
mn_check_include_file (sys/stat.h		HAVE_SYS_STAT_H)
mn_check_include_file (sys/time.h		HAVE_SYS_TIME_H)
mn_check_include_file (sys/types.h		HAVE_SYS_TYPES_H)
mn_check_include_file (sys/wait.h		HAVE_SYS_WAIT_H)
mn_check_include_file (unistd.h			HAVE_UNISTD_H)


mn_check_type_size (double 			SIZEOF_DOUBLE)
mn_check_type_size (float 			SIZEOF_FLOAT)
mn_check_type_size (int 			SIZEOF_INT)
mn_check_type_size (int64_t 		SIZEOF_INT64_T)
mn_check_type_size (loff_t 			SIZEOF_LOFF_T)
mn_check_type_size (long 			SIZEOF_LONG)
mn_check_type_size (long\ long 		SIZEOF_LONG_LONG)
mn_check_type_size (offt64_t 		SIZEOF_OFF64_T)
mn_check_type_size (off_t 			SIZEOF_OFF_T)
mn_check_type_size (short 			SIZEOF_SHORT)
mn_check_type_size (size_t 			SIZEOF_SIZE_T)
mn_check_type_size (ssize_t 		SIZEOF_SSIZE_T)
mn_check_type_size (void* 			SIZEOF_VOIDP)
mn_check_type_size (xxwchar_t 		SIZEOF_WCHAR_T)

set (SIZEOF_SF_COUNT_T ${SIZEOF_INT64_T})
set (TYPEOF_SF_COUNT_T int64_t)

# Can't figure out how to make CMAKE_COMPILER_IS_GNUCC set something to either
# 1 or 0 so we do this:
mn_try_compile_c_result (CMake/compiler_is_gcc.c COMPILER_IS_GCC 1 0)

TEST_BIG_ENDIAN (BIGENDIAN)
if (${BIGENDIAN})
	set (WORDS_BIGENDIAN 1)
	set (CPU_IS_BIG_ENDIAN 1)
	set (CPU_IS_LITTLE_ENDIAN 0)
else (${BIGENDIAN})
	set (WORDS_BIGENDIAN 0)
	set (CPU_IS_LITTLE_ENDIAN 1)
	set (CPU_IS_BIG_ENDIAN 0)
	endif (${BIGENDIAN})

if (${WINDOWS})
	set (OS_IS_WIN32 1)
else (${WINDOWS})
	set (OS_IS_WIN32 0)
	endif (${WINDOWS})


mn_check_library_exists (m floor "" HAVE_LIBM)
mn_check_library_exists (sqlite3 sqlite3_close "" HAVE_SQLITE3)

mn_check_function_exists (calloc		HAVE_CALLOC)
mn_check_function_exists (free			HAVE_FREE)
mn_check_function_exists (fstat			HAVE_FSTAT)
mn_check_function_exists (fstat64		HAVE_FSTAT64)
mn_check_function_exists (fsync			HAVE_FSYNC)
mn_check_function_exists (ftruncate		HAVE_FTRUNCATE)
mn_check_function_exists (getpagesize	HAVE_GETPAGESIZE)
mn_check_function_exists (gettimeofday	HAVE_GETTIMEOFDAY)
mn_check_function_exists (gmtime		HAVE_GMTIME)
mn_check_function_exists (gmtime_r		HAVE_GMTIME_R)
mn_check_function_exists (localtime		HAVE_LOCALTIME)
mn_check_function_exists (localtime_r	HAVE_LOCALTIME_R)
mn_check_function_exists (lseek			HAVE_LSEEK)
mn_check_function_exists (lseek64		HAVE_LSEEK64)
mn_check_function_exists (malloc		HAVE_MALLOC)
mn_check_function_exists (mmap			HAVE_MMAP)
mn_check_function_exists (open			HAVE_OPEN)
mn_check_function_exists (pipe			HAVE_PIPE)
mn_check_function_exists (read			HAVE_READ)
mn_check_function_exists (realloc		HAVE_REALLOC)
mn_check_function_exists (setlocale		HAVE_SETLOCALE)
mn_check_function_exists (snprintf		HAVE_SNPRINTF)
mn_check_function_exists (vsnprintf		HAVE_VSNPRINTF)
mn_check_function_exists (waitpid		HAVE_WAITPID)
mn_check_function_exists (write			HAVE_WRITE)

mn_check_math_function_exists (ceil		HAVE_CEIL)
mn_check_math_function_exists (floor 	HAVE_FLOOR)
mn_check_math_function_exists (fmod  	HAVE_FMOD)
mn_check_math_function_exists (lrint	HAVE_LRINT)
mn_check_math_function_exists (lrintf	HAVE_LRINTF)
mn_check_math_function_exists (lround	HAVE_LROUND)
